### ISSUE TITLE
environment error

### ISSUE THREAD

**Issue by JingqiKang** [allenai/drug-combo-extraction#48]
I tried to run the training command, but encountered this error:
from torchmetrics.utilities.data import get_num_classes as _get_num_classes
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data'

**Comment by JingqiKang** [comment]
![image](https://user-images.githubusercontent.com/88081081/192279379-c26894e5-cff1-4c58-b1d1-c8cc2df38cfa.png)

**Comment by JingqiKang** [comment]
sorry to bother you again. 
I installed the 0.5.0 version, but I encountered this error
![image](https://user-images.githubusercontent.com/88081081/192425081-8ec885e8-710b-46f9-ad40-6ec1242ced2e.png)

**Comment by viswavi** [comment]
I'm not sure exactly what this problem is, but I was able to reproduce a similar error on my computer, and fixed it using [this Github issue](https://github.com/pytorch/pytorch/issues/69894), which gives this fix:

```
pip install setuptools==59.5.0
```

Try this?

**Comment by JingqiKang** [comment]
There is another error
![image](https://user-images.githubusercontent.com/88081081/192658501-e4a94ba0-53ee-4cc4-8722-a42a3d6bc105.png)

**Comment by JingqiKang** [comment]
I have found the solution：pip install 'protobuf~=3.19.0'

**Comment by viswavi** [comment]
Great, any other errors? I'm online if you need live help debugging
anything
Thank you for finding these issues, I will update the requirements.txt file

**Comment by JingqiKang** [comment]
Thank you！I will try it myself first, and then communicate with you if I have any questions, many thanks!
