### ISSUE TITLE
Unable to load the model "allenai / drug-combo-classifier-pubmedbert-dapt"

### ISSUE THREAD

**Issue by yuhangjiang22** [allenai/drug-combo-extraction#51]
Can't load it either following the command line in [HuggingFace](https://huggingface.co/allenai/drug-combo-classifier-pubmedbert-dapt) or using `transformers.AutoModel.from_pretrained('allenai/drug-combo-classifier-pubmedbert-dapt')`

Is there a way to easily load it similar to other HuggingFace models?

**Comment by viswavi** [comment]
Hi @yuhangjiang22 , I was earlier working on making this model easily loadable via HuggingFace but got sidetracked by other obligations. If the community feels this is sufficiently important, I can try to prioritize this task myself. In the meanwhile, we welcome contributions from the community.

Regarding that error, I am not familiar with it. Can you share the full stack trace?

There was also a typo in the Huggingface documentation  (which I've fixed) - the instructions should have spaces:

```
from modeling.model import load_model
checkpoint_path = "checkpoints_pubmedbert_cpt_2021_three_class"
model, tokenizer, metadata = load_model(checkpoint_path)
```

**Comment by yuhangjiang22** [comment]
Thank you for reply! @viswavi 
Here's the full stack trace:
`Traceback (most recent call last):
  File "/Users/kaka/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-28-20afc7eb6937>", line 1, in <module>
    model, tokenizer, metadata = load_model(checkpoint_path)
  File "./modeling/model.py", line 260, in load_model
    tokenizer = AutoTokenizer.from_pretrained(metadata.model_name, do_lower_case=True)
  File "/Users/kaka/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 471, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/Users/kaka/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 332, in get_tokenizer_config
    resolved_config_file = get_file_from_repo(
  File "/Users/kaka/lib/python3.8/site-packages/transformers/utils/hub.py", line 678, in get_file_from_repo
    resolved_file = cached_path(
  File "/Users/kaka/lib/python3.8/site-packages/transformers/utils/hub.py", line 282, in cached_path
    output_path = get_from_cache(
  File "/Users/kaka/lib/python3.8/site-packages/transformers/utils/hub.py", line 545, in get_from_cache
    raise ValueError(
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.
`

Do you have any idea why this happens?

**Comment by viswavi** [comment]
I have no idea about this particular error, to be honest. However, I did try (and fail) to run the Huggingface model (as listed in the README) on a new machine, so I think there was a problem.

I restructured the [model on Huggingface](https://huggingface.co/allenai/drug-combo-classifier-pubmedbert-dapt) a bit (most importantly, I've moved the base LM we trained to [a separate HF model](https://huggingface.co/allenai/drug_combinations_lm_pubmedbert?text=Paxlovid+works+well+in+combination+with+%5BMASK%5D+for+treating+breast+cancer.)). I tested the new model and instructions on a new machine and it works, so hopefully it works for you too?

Let me know.
